### ISSUE TITLE
Текущие замечания

### ISSUE THREAD

**Issue by krsch** [Vsevolod-pl/Programming_game#1]
- [x] Не все документированы.
- [x] Совсем нет документации о том, как писать своего бота.
- [x] А бот хоть что-то знает о поле? Как он вообще решения принимать должен?
- [x] Кода на python мало.
- [x] Тестов нет вообще.
- [x] Нет возможности запуска всех необходимых программ в одну команду.

**Comment by Vsevolod-pl** [comment]
Fixed all problems!
